namespace SpriteKind {
    export const npc = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile4`, function (sprite, location) {
    if (Level == 2) {
        Level += 1
        Level_3()
    } else {
        game.over(true)
    }
})
info.onCountdownEnd(function () {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite, location) {
    Level += 1
    Level_2()
})
info.onLifeZero(function () {
    game.over(false)
})
function Level_3 () {
    tiles.setCurrentTilemap(tilemap`level9`)
    tiles.placeOnRandomTile(Character, assets.tile`myTile7`)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    sprites.destroyAllSpritesOfKind(SpriteKind.npc)
    Vroom_Vroom = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . 2 2 2 2 2 2 . . . . 
        . . . . . 2 2 4 4 2 2 2 2 . . . 
        . . . . . c 4 2 2 2 2 2 c . . . 
        . . . . 2 c 4 2 2 2 2 2 c 2 . . 
        . . . e 2 c 4 2 2 2 2 2 c 2 e . 
        . . . f 2 c 4 2 2 2 2 2 c 2 f . 
        . . . f e c 2 2 2 2 2 2 c e f . 
        . . . f 2 c 2 b b b b 2 c 2 f . 
        . . . e 2 2 b c c c c b 2 2 e . 
        . . . e e b c c c c c c b e e . 
        . . . f e 4 4 4 4 4 4 4 4 e f . 
        . . . f e d 2 2 2 2 2 2 d e f . 
        . . . . 2 d d 2 2 2 2 d d 2 f . 
        . . . . f 2 d 2 2 2 2 d 2 f . . 
        . . . . . e 2 2 2 2 2 2 e . . . 
        `, SpriteKind.Player)
    tiles.placeOnRandomTile(Vroom_Vroom, assets.tile`myTile6`)
    Vroom_Vroom.setVelocity(100, 100)
}
function Level_2 () {
    info.stopCountdown()
    info.setLife(450)
    game.splash("You are in level 2", "You must beat the BOSS THAT HAS A SWARD AND DOES LOTS OF DAMAGE AND THATS WHY YOU HAVE 450 HEARTS")
    game.splash("You must beat Biggie cheese and he multiplys ")
    game.splash("You must get the odd yellow block that looks ugly because I dont know how to draw")
    game.splash("Thats how you win")
    tiles.setCurrentTilemap(tilemap`level6`)
    for (let index = 0; index < 5; index++) {
        mySprite = sprites.create(img`
            ..................................................
            .............................ffffffffffff.........
            .............................f..........f.........
            .............................f..........f.........
            .........................f...f..f.......f.........
            .........................f...f......f...f.........
            .........................f...f..........f.........
            .........................f...f...fffff..f.........
            .........................f...f...f...f..f.........
            .......................11111.f..........f.........
            ...........................1.ffffffffffff.........
            ...........................1.......f..............
            ...........................ff......f.ffff.........
            ............................ffffffffff..ff........
            ...................................f.....ff.......
            ...................................f..............
            ...................................f..............
            .................................ffff.............
            ................................ff..ff............
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            `, SpriteKind.Enemy)
        tiles.placeOnRandomTile(mySprite, assets.tile`myTile5`)
        mySprite.follow(Character)
    }
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
})
let jump = 0
let mySprite: Sprite = null
let Vroom_Vroom: Sprite = null
let qpqp: Sprite = null
let Character: Sprite = null
let Level = 0
Level = 0
game.splash("Climb to the top to beat level 1")
game.splash("use button a to jump")
game.splash("use the left and right arrow key to move")
Character = sprites.create(img`
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    .................1111...................
    ..............111ffff11.................
    ..............1fff11ff1.................
    .............11f11111f1.................
    .............1ff1f11f1f11...............
    .............1f1111111ff11..............
    .............1f1fffff11ff1..............
    .............1f111111111f1..............
    .............11fffffffff11..............
    ..............11111f1111................
    ..........11......1f1.....11............
    ..........1f111...1f111111f1............
    ..........1f111111fff1111ff1............
    ..........11ffffffffffffff..............
    ............111111fff1..................
    .................1fff1..................
    .................1fff1..................
    .................11f11..................
    .................11f11..................
    ................111f11..................
    ...............1fffff111................
    ..............11ff11ff111...............
    .............11ff1..1ff11...............
    .............1ff11..1fff1...............
    ...........1ffff1....1fff1..............
    ............111.......111...............
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    `, SpriteKind.Player)
scene.setBackgroundColor(6)
tiles.setCurrentTilemap(tilemap`level1`)
tiles.placeOnRandomTile(Character, assets.tile`myTile0`)
for (let index = 0; index < 50; index++) {
    qpqp = sprites.create(img`
        . . . . . . . . 1 1 . . . . . . 
        . . . . . . 1 1 1 1 1 . . . . . 
        . . . . 1 1 1 1 1 1 1 1 . . . . 
        1 1 1 1 1 1 1 1 1 1 1 1 1 . . . 
        1 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        1 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        1 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . . . . . . 1 1 1 1 1 1 . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.npc)
    qpqp.setPosition(randint(0, 250), randint(0, 2000))
}
scene.cameraFollowSprite(Character)
Character.ay = 450
Character.setStayInScreen(true)
controller.moveSprite(Character, 100, 0)
info.startCountdown(35)
forever(function () {
    if (controller.A.isPressed()) {
        jump += 1
        Character.vy = -400
        pause(1400)
        jump = 0
    } else if (jump == 1) {
        Character.ay = 450
    }
})
forever(function () {
    music.playMelody("A G B E C5 A D B ", 400)
})
