namespace SpriteKind {
    export const npc = SpriteKind.create()
    export const cer = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile4`, function (sprite, location) {
    Level_3()
})
info.onCountdownEnd(function () {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite, location) {
    Level_2()
})
info.onLifeZero(function () {
    game.over(false)
})
function Level_3 () {
    tiles.setCurrentTilemap(tilemap`level9`)
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    tiles.placeOnRandomTile(Character, sprites.castle.tileGrass1)
    sprites.destroyAllSpritesOfKind(SpriteKind.npc)
    for (let index = 0; index < 3; index++) {
        vroom_vroom = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . 2 2 2 2 2 2 . . . . 
            . . . . . 2 2 4 4 2 2 2 2 . . . 
            . . . . . c 4 2 2 2 2 2 c . . . 
            . . . . 2 c 4 2 2 2 2 2 c 2 . . 
            . . . e 2 c 4 2 2 2 2 2 c 2 e . 
            . . . f 2 c 4 2 2 2 2 2 c 2 f . 
            . . . f e c 2 2 2 2 2 2 c e f . 
            . . . f 2 c 2 b b b b 2 c 2 f . 
            . . . e 2 2 b c c c c b 2 2 e . 
            . . . e e b c c c c c c b e e . 
            . . . f e 4 4 4 4 4 4 4 4 e f . 
            . . . f e d 2 2 2 2 2 2 d e f . 
            . . . . 2 d d 2 2 2 2 d d 2 f . 
            . . . . f 2 d 2 2 2 2 d 2 f . . 
            . . . . . e 2 2 2 2 2 2 e . . . 
            `, SpriteKind.cer)
        tiles.placeOnRandomTile(vroom_vroom, assets.tile`myTile8`)
        mySprite.vy = 100
    }
}
function Level_2 () {
    info.stopCountdown()
    info.setLife(450)
    game.splash("You are in level 2", "You must beat the BOSS THAT HAS A SWARD AND DOES LOTS OF DAMAGE AND THATS WHY YOU HAVE 450 HEARTS")
    game.splash("You must beat power man and he multiplys ")
    game.splash("You must get the odd yellow block that looks ugly because I dont know how to draw")
    game.splash("Thats how you win")
    tiles.setCurrentTilemap(tilemap`level6`)
    for (let index = 0; index < 5; index++) {
        mySprite = sprites.create(img`
            ..................................................
            .............................ffffffffffff.........
            .............................f..........f.........
            .............................f..........f.........
            .........................f...f..f.......f.........
            .........................f...f......f...f.........
            .........................f...f..........f.........
            .........................f...f...fffff..f.........
            .........................f...f...f...f..f.........
            .......................11111.f..........f.........
            ...........................1.ffffffffffff.........
            ...........................1.......f..............
            ...........................ff......f.ffff.........
            ............................ffffffffff..ff........
            ...................................f.....ff.......
            ...................................f..............
            ...................................f..............
            .................................ffff.............
            ................................ff..ff............
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            ..................................................
            `, SpriteKind.Enemy)
        tiles.placeOnRandomTile(mySprite, assets.tile`myTile5`)
        mySprite.follow(Character)
    }
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
})
let score = 0
let mySprite: Sprite = null
let vroom_vroom: Sprite = null
let qpqp: Sprite = null
let Character: Sprite = null
game.splash("Climb to the top to beat level 1")
game.splash("use button a to jump")
game.splash("use the left and right arrow key to move")
Character = sprites.create(img`
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ................111111..................
    ..............111ffff11.................
    ..............1fff11ff11................
    .............11f11111ff1................
    .............1fff111f1f11...............
    .............1f11111111f11..............
    .............1f1fffff11ff1..............
    .............1f111111111f1..............
    .............1fffffffffff1..............
    .............111111ff11111111...........
    ..........1111....1f11...1ff1...........
    ..........1f111..11f11..11ff1...........
    ..........1fff1111fff1111fff1...........
    ..........111ffffffffffff1111...........
    ............111111fff11111..............
    .................1fff1..................
    .................1fff1..................
    .................11f11..................
    ..................1f1...................
    .............111111f111.................
    .............11fffffff11................
    .............1ffff11fff11...............
    .............1fff111ffff1...............
    ............11ff11.11fff11..............
    ............1ff11...11fff1..............
    ............1111.....11111..............
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    `, SpriteKind.Player)
scene.setBackgroundColor(6)
tiles.setCurrentTilemap(tilemap`level1`)
tiles.placeOnRandomTile(Character, assets.tile`myTile0`)
for (let index = 0; index < 50; index++) {
    qpqp = sprites.create(img`
        . . . . . . . . 1 1 . . . . . . 
        . . . . . . 1 1 1 1 1 . . . . . 
        . . . . 1 1 1 1 1 1 1 1 . . . . 
        1 1 1 1 1 1 1 1 1 1 1 1 1 . . . 
        1 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        1 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        1 1 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
        . . . . . . 1 1 1 1 1 1 . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.npc)
    qpqp.setPosition(randint(0, 250), randint(0, 2000))
}
scene.cameraFollowSprite(Character)
Character.ay = 450
Character.setStayInScreen(true)
controller.moveSprite(Character, 100, 0)
info.startCountdown(35)
forever(function () {
    if (controller.A.isPressed()) {
        score += 1
        Character.vy = -400
        pause(1400)
        score = 0
    } else if (score == 1) {
        Character.ay = 450
    }
})
forever(function () {
    music.playMelody("A G B E C5 A D B ", 400)
})
